// <auto-generated />
namespace iTrellisApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_statusVm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_statusVm));
        
        string IMigrationMetadata.Id
        {
            get { return "201605240407464_added_statusVm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
